### ISSUE TITLE
规划填写规划层级后产生bug

### ISSUE THREAD

**Issue by Morningssir** [Morningssir/Onps-workflow#16]
## Description
规划面板填写规划层后，显示规划失败

## Test case
level2B用户下test4-25项目

## Screenshot
![image.png](https://images.zenhubusercontent.com/6046dee9151cf26de4f2f261/08db530c-5214-4e55-bda4-ac6ae32a69ce)
![image.png](https://images.zenhubusercontent.com/6046dee9151cf26de4f2f261/f0f0233b-5f57-488e-9fa0-3360735a4c05)

**Comment by lioneye63** [comment]
已解决
