### ISSUE TITLE
业务恢复率NAN问题

### ISSUE THREAD

**Issue by moncaroline** [Morningssir/Onps-workflow#21]
##Description
操作的项目为level1A的“提报bug测试2”项目，项目id为P_2021_04_26_00012_A，此项目没有节点、链路和业务，在测试业务恢复率时，出现了数据转换问题
### Screenshot
![d76a99125cdce90f7d6b82038bb9583.png](https://images.zenhubusercontent.com/608127b815fc34642568da2c/35a201e0-9b6a-4bed-866f-7ef7913cc671)

**Comment by lioneye63** [comment]
已解决
