### ISSUE TITLE
规划接口产生的部分bug

### ISSUE THREAD

**Issue by Morningssir** [Morningssir/Onps-workflow#4]
## Description
1. 规划结果采用set导致顺序错乱问题
2. 部分业务规划失败，获取项目接口可以看到不存在规划路由，但是获取规划信息接口依然能获取到路由信息
3. 业务信息需要包含一个变量存储当前业务规划的状态 'success' 'error' 'default'，建议这三种状态标识

## Issues
- [x] 合肥1-福州1业务工作路由存在问题
- [x] 兰州2-乌鲁木齐1保护路由有问题
- [x] 成都2-贵阳1工作路由有问题

## Motivations
1. 问题普遍集中于节点列表

**Comment by lioneye63** [comment]
1.WeaverResultData.workRoute/protectRoute.nodeList/linklist类型由set变成list
2.WeaverResultData.workRoute/protectRoute只保留规划成功的业务id为key
3.WeaverResultData新增Map<serviceId, String> planStatus，value为"success"或"error"

**Comment by Morningssir** [comment]
业务返回信息需要进一步增强
1. `status`标识`success` `error` `default`三种状态，`default`主要标识**未规划**的状态
2. `reason`标识中文具体原因，例如**保护路由无法承载**
