### ISSUE TITLE
规划部分规划失败问题

### ISSUE THREAD

**Issue by fff1216** [Morningssir/Onps-workflow#43]
# description
存在相应节点、链路，带宽也满足但却规划失败了
# screenshot
![image.png](https://images.zenhubusercontent.com/606ac31b638863afa441a3ed/fb3316b1-8f0f-4e5d-9090-1e3f0f2f0fe5)
![image.png](https://images.zenhubusercontent.com/606ac31b638863afa441a3ed/8002de94-8f50-4e3c-bf67-fe7af9313f5b)

**Comment by lioneye63** [comment]
增加判断条件：必经节点即是首节点/末节点的情况
